version: '3'
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: en3m
    ports:
      - "27017:27017"
    #volumes:
    #  - /home/diegolirio/MongoDB:/data/db
    networks:
      - kong

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: diegolirio
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: en3m
    links:
      - mongo
    networks:
      - kong

networks:
  kong:
    driver: bridge