spring:
  profiles.active: dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:en3mlocalhost:27017/enemdb}
      #database: employee-service-blog
      #host: employeemongodb
      #port: 27017